language: android
jdk: oraclejdk7

android:
  components:
    - platform-tools
    - build-tools-21
    - android-21.0.2
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.*

install: true # Override install task to prevent duplicate assembleDebug task invocation

script: ./gradlew testDebug -Dpre-dex=false --info